namespace Common.Enums
{
    public enum EmailType
    {
        REGISTRATION = 1,
        FORGET_PASSWOD = 2,
        TRIP_DONE = 3,
        TRIP_DONE_NO_OFFERS = 4,
        TRIP_CLOSE_NO_ACCEPTED_OFFER = 5,
        TRIP_OFFER_ACCEPTED_25_DEMANDER = 6,
        TRIP_OFFER_ACCEPTED_100_DEMANDER = 7,
        TRIP_OFFER_ACCEPTED_TRANSPORTER = 8,
        TRIP_OFFER_PAYED_25_FOR_TRANSPORTER = 9,
        TRIP_OFFER_PAYED_25_FOR_DEMANDER = 10,
        TRIP_OFFER_PAYED_75_FOR_TRANSPORTER = 11,
        TRIP_OFFER_PAYED_75_FOR_DEMANDER = 12,
        TRIP_OFFER_PAYED_100_FOR_TRANSPORTER = 13,
        TRIP_OFFER_PAYED_100_FOR_DEMANDER = 14,
        TRIP_OFFER_CLOSED_DEMANDER = 15,
        TRIP_OFFER_CLOSED_UNPAID_25_DEMANDER = 16,
        TRIP_OFFER_CLOSED_UNPAID_75_DEMANDER = 17,
        TRIP_OFFER_CLOSED_UNPAID_100_DEMANDER = 18,
        TRIP_OFFER_CLOSED_TRANSPORTER = 19,
        TRIP_OFFER_CLOSED_UNPAID_25_TRANSPORTER = 20,
        TRIP_OFFER_CLOSED_UNPAID_75_TRANSPORTER = 21,
        TRIP_OFFER_CLOSED_UNPAID_100_TRANSPORTER = 22,
        TRIP_OFFER_PAY_WARNING_SET_25 = 23,
        TRIP_OFFER_PAY_WARNING_SET_100 = 24,
        TRIP_OFFER_PAY_WARNING_PAYED_25 = 25,
        TRIP_NEW_OFFER_FROM_TRANSPORTER = 26,
        TRIP_CREATE = 27,
        TRIP_OFFER_PAY_COMMISSION_TRANSPORTER = 28
    }
    public enum EmailParams
    {
        TRIP_DETAIL_LINK,
        PERCENT,
        RESET_PASSWORD_LINK,
        ACTIVE_USER_LINK
    }

    public enum UserParams
    {
        Role,
        Name,
        Surname,
        PhoneNumber
    }

    public enum SendinblueListType
    {
        MAIN
    }
}
